#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

if [[ ! -f .env ]]; then
  echo "error: .env not found. Copy .env.example to .env and fill in values." >&2
  exit 1
fi

set -a
# shellcheck disable=SC1091
source .env
set +a

: "${SUPABASE_URL:?SUPABASE_URL missing in .env}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY missing in .env}"

cat > config.js <<EOF
// Generated by build-config.sh from .env — do not edit by hand.
window.PANCHAM_CONFIG = {
  SUPABASE_URL: "${SUPABASE_URL}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
};
EOF

echo "Wrote config.js"
